#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create directories and files
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo sh -c 'echo "Hello World!" > /etc/nginx/html/index.html'

# Configure Nginx
sudo sh -c 'printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
sudo service nginx restart

