#!/usr/bin/env bash

# Script that installs Nginx server and configures a custom 404 page

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create directories and files
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo sh -c "echo "Ceci n\'est pas une page" > /etc/nginx/html/404.html"

# Configure Nginx
sudo sh -c 'printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    server_name _;

    location / {
        return 404 /404.html;
    }

    error_page 404 /404.html;
    location /404 {
        internal;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
sudo service nginx restart
