#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo apt-get update
sudo apt-get install -y nginx


# Edit the Nginx configuration to listen on port 80 of all active IPv4 IPs
sed -i '/listen \[::\]:80 default_server;/d' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server;/d' /etc/nginx/nginx.conf
echo "listen 80 default_server;" >> /etc/nginx/nginx.conf

sudo service nginx restart
