#!/usr/bin/env bash
# SSH client configuration

Host *
#   ForwardAgent no
#   PasswordAuthentication no
#   IdentityFile ~/.ssh/school
#   SendEnv LANG LC_*
#   HashKnownHosts yes
#   GSSAPIDelegateCredentials no
#   GSSAPIAuthentication yes
